### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ajiragroup** [TridotsTech/Go1-Webshop#7]
Getting this error during installation:

```
user@Laptop-AD:~/frappe-bench$ bench --site site2.local install-app go1_webshop
App erpnext already installed
Could not find app "webshop":
No module named 'webshop'
An error occurred while installing go1_webshop: No module named 'webshop'
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 452, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['site2.local'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('go1_webshop',)
      force = False
      _install_app = <function install_app at 0x7f206b5dd630>
      filelock = <function filelock at 0x7f206b5c75b0>
      exit_code = 0
      site = 'site2.local'
      app = 'go1_webshop'
      err = ModuleNotFoundError("No module named 'webshop'")
  File "apps/frappe/frappe/installer.py", line 284, in install_app
    install_app(required_app, verbose=verbose)
      name = 'go1_webshop'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7f206ab7b880>
      sync_for = <function sync_for at 0x7f206a9943a0>
      sync_customizations = <function sync_customizations at 0x7f206c57ab00>
      sync_fixtures = <function sync_fixtures at 0x7f206a9945e0>
      app_hooks = {'after_migrate': ['go1_webshop.go1_webshop.after_install.insert_theme_selection_details'], 'app_description': ['Ecommerce app'], 'app_email': ['info@tridotstech.com'], 'app_license': ['mit'], 'app_name': ['go1_webshop'], 'app_publisher': ['tridotstech'], 'app_title': ['Go1 Webshop'], 'doc_events': {'Builder Page': {'on_update': ['go1_webshop.go1_webshop.api.update_global_script']}, 'Builder Settings': {'on_update': ['go1_webshop.go1_webshop.api.update_global_script_builder_page']}, 'Website Item': {'validate': ['go1_webshop.go1_webshop.api.update_website_item_route']}, 'Item Group': {'validate': ['go1_webshop.go1_webshop.api.update_website_item_route']}}, 'required_apps': ['erpnext', 'webshop', 'builder']}
      installed_apps = ['frappe', 'erpnext', 'hrms']
      app = 'webshop'
      required_app = 'webshop'
  File "apps/frappe/frappe/installer.py", line 277, in install_app
    app_hooks = frappe.get_hooks(app_name=name)
      name = 'webshop'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7f206ab7b880>
      sync_for = <function sync_for at 0x7f206a9943a0>
      sync_customizations = <function sync_customizations at 0x7f206c57ab00>
      sync_fixtures = <function sync_fixtures at 0x7f206a9945e0>
  File "apps/frappe/frappe/__init__.py", line 1645, in get_hooks
    hooks = _dict(_load_app_hooks(app_name))
      hook = None
      default = '_KEEP_DEFAULT_LIST'
      app_name = 'webshop'
  File "apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
      args = ('webshop',)
      kwargs = {}
      args_key = ********
      func = <function _load_app_hooks at 0x7f206cb8b1c0>
  File "apps/frappe/frappe/__init__.py", line 1617, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
      app_name = 'webshop'
      hooks = {}
      apps = ['webshop']
      app = 'webshop'
      types = <module 'types' from '/usr/lib/python3.10/types.py'>
  File "apps/frappe/frappe/__init__.py", line 1483, in get_module
    return importlib.import_module(modulename)
      modulename = 'webshop.hooks'
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
      name = 'webshop.hooks'
      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      name = 'webshop.hooks'
      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      name = 'webshop.hooks'
      import_ = <function _gcd_import at 0x7f206e2a3400>
      module = <exception while printing> Traceback (most recent call last):
          File "env/lib/python3.10/site-packages/traceback_with_variables/core.py", line 222, in _to_cropped_str
            raw = print_(obj)
          File "apps/frappe/frappe/utils/__init__.py", line 328, in dict_printer
            if key in v:
        TypeError: argument of type 'object' is not iterable

  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
      name = 'webshop.hooks'
      import_ = <function _gcd_import at 0x7f206e2a3400>
      path = None
      parent = 'webshop'
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      f = <function _gcd_import at 0x7f206e2a3400>
      args = ('webshop',)
      kwds = {}
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      name = 'webshop'
      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      name = 'webshop'
      import_ = <function _gcd_import at 0x7f206e2a3400>
      module = <exception while printing> Traceback (most recent call last):
          File "env/lib/python3.10/site-packages/traceback_with_variables/core.py", line 222, in _to_cropped_str
            raw = print_(obj)
          File "apps/frappe/frappe/utils/__init__.py", line 328, in dict_printer
            if key in v:
        TypeError: argument of type 'object' is not iterable

  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
      name = 'webshop'
      import_ = <function _gcd_import at 0x7f206e2a3400>
      path = None
      parent = ''
      spec = None
builtins.ModuleNotFoundError: No module named 'webshop'
```

**Comment by TridotsTech** [comment]
hi, you need to install the apps erpnext,webshop,builder before installing go1 webshop app.
